### ISSUE TITLE
Short instruction connecting video to repo would be helpful.

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/bootstrap-codealong#1]
Based on the lessons I've followed to this point, I found that following the video exactly, would accomplish the lesson.     In this case, it is not obvious that the repo in this lesson is the place where you are supposed to put the exceptional-realty-bootstrapped folder. 

Perhaps a guiding instruction like:   Fork and clone down the repo and use that for where you store your exceptiona-realty-boostrapped code.

**Comment by AnnJohn** [comment]
thanks @smithWEBtek for raising this issue. we definitely will be improving our curriculum and we know that these particular labs need a bit more love. thanks again!

**Comment by smithWEBtek** [comment]
Hi Ann,   I am having the same error on a 3rd lab now, and wondering if it is something that has gotten misconfigured on my system?     I have posted bug reports on the first 2 labs that had this issue in my case, I will do the same on the 3rd lab, and will use the Ask a Question feature to see if someone can confirm whether or not it is my system at fault, or if it truly is a bug.

**Comment by jongrover** [comment]
never got to this sorry.

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #24.
-- Flatiron Curriculum Team
