### ISSUE TITLE
REPLACE BOOTSTRAP CODEALONG VIDEO

### ISSUE THREAD

**Issue by DoriansGrave** [learn-co-curriculum/bootstrap-codealong#11]
This video is entirely out of date. The supplementary instructions are useless. It's unacceptable that an entire introduction to a brand new subject would be completely unusable. ALL of the "exceptional realty" videos are outdated. These need to be replaced immediately; how old is the message saying it would be updated "ASAP"? This is what you are being paid to do.

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #24. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
