### ISSUE TITLE
Can't seem to follow in Learn IDE

### ISSUE THREAD

**Issue by eyosef** [learn-co-curriculum/bootstrap-codealong#13]
I attempted to use Learn IDE to follow along, but unfortunately I was not able to access my download folder in my computer to unzip the bootstrap file. Other than the folder I created for my labs, I did not create a git repository for all files in my computer. It would be very helpful if there was information earlier describing how to connect all necessary files to a repository. 

It also seems that Learn IDE could not access my git repository when it opens a temporary session. As a result, I could not access files that my git repository typically has access to.

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #24.
-- Flatiron Curriculum Team
