### ISSUE TITLE
Need content for future codealong, but instructed to not submit

### ISSUE THREAD

**Issue by ahotchkin** [learn-co-curriculum/bootstrap-codealong#15]
There is a note under the codealong video: Finally, because this is a simple code-along, you won't actually have to submit anything at the end (unlike in the video).

I think you may need to submit this because this material is necessary for the layouts-grids-code-along and it's not already built into that lab when you open the IDE.

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #24.

-- Flatiron Curriculum Team
