### ISSUE TITLE
No fork and submit

### ISSUE THREAD

**Issue by kirbycampbell** [learn-co-curriculum/bootstrap-codealong#16]
Hi, can this lesson be changed to "Done reading" so we can check this one off in our curriculum?  Right now its set up for forking, (yet you can't) and it has "learn submit" yet its not accepted.  Thanks

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #24. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
