### ISSUE TITLE
Can we get this one fixed?

### ISSUE THREAD

**Issue by kirbycampbell** [learn-co-curriculum/bootstrap-codealong#17]
I still cant fork/submit to get the green checkbox next to this lab.  It's messing with my organizational OCD in the learning path on Learn.co.  Thanks,
Kirby

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #24. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
