### ISSUE TITLE
Can we turn this lesson into the "Done" click box?

### ISSUE THREAD

**Issue by kirbycampbell** [learn-co-curriculum/bootstrap-codealong#18]
There's nothing to submit or fork, and it's keeping my html/css section unmarked as finished even though I finished the lesson.  Easy fix.

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #24. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
