### ISSUE TITLE
not showing as completed

### ISSUE THREAD

**Issue by dmcgrann** [learn-co-curriculum/bootstrap-codealong#19]
Hi --

I am having the same issues that a few others had. I have completed it and clicked "done," but it still shows incomplete in my list, so the whole HTML/CSS section shows as incomplete. Could you please fix this.

Thank you

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #24. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
