### ISSUE TITLE
Status not changing to 'completed'

### ISSUE THREAD

**Issue by rfenix3** [learn-co-curriculum/bootstrap-codealong#20]
Hi tech support, 
I've read other folks having similar issue as mine. I've completed the lesson and moved on to the next lessons but this lesson remains 'uncompleted' status. What is the fix for this? Is there something I should do?
regards,
Richard

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #24. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
