### ISSUE TITLE
Lesson not being marked as complete

### ISSUE THREAD

**Issue by BrownCow371** [learn-co-curriculum/bootstrap-codealong#21]
Hello!  This lesson is not being marked as complete, even thought the finished reading button has been clicked. 
![2018-08-08_092904](https://user-images.githubusercontent.com/39419690/43840025-9f4936dc-9aed-11e8-8b73-4bff5d1d6682.jpg)

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #24. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
