### ISSUE TITLE
Just a few pointers to get you by this code along...

### ISSUE THREAD

**Issue by wendisha** [learn-co-curriculum/bootstrap-codealong#22]
Two things to keep in mind:
-Importing the files will not work from the browser IDE. I had to set up the IDE for this (not complaining, I like it here 👍 ).
-New link for the html basic template: https://getbootstrap.com/docs/4.1/getting-started/introduction/#starter-template

Happy coding!

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #24.

-- Flatiron Curriculum Team
