### ISSUE TITLE
Not Showing As Completed.

### ISSUE THREAD

**Issue by georgepianka** [learn-co-curriculum/bootstrap-codealong#23]
Seems like some people are getting the Bootstrap Codealong checked off, Some Not. Reached out to Tech Support. They have no Idea. Clearly This has been an issue for a long time. 
Any updates?

**Comment by NirvashPrime** [comment]
I'm seeing the very same behavior unfortunately.

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #24. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
