### ISSUE TITLE
Lab doesn't acknowledge forked repo

### ISSUE THREAD

**Issue by dkennell** [learn-co-curriculum/bootstrap-codealong#6]
I've forked the github repo for this lab in every way I can think of, but the lab won't acknowledge it. I've forked it from the github repo directly to my github account, and I've opened it with the 'learn' button. I tried cloning it from terminal as well, but nothing changes. I'm passing the "Submitted Pull Request" test, but I can't get "Fork this Lab" to go green.

**Comment by AnnJohn** [comment]
hi @dkennell sorry about this. Since this is a product bug, could you file a bug report? If you hover over your profile pic in Learn, you'll see an option to Report a Bug. Thanks!

**Comment by dkennell** [comment]
WIll do, thanks!
