### ISSUE TITLE
Pull request or no?

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/bootstrap-codealong#9]
On the one hand, the sidebar asks the student to submit a pull request.

On the other hand, the README.md says: "Finally, because this is a simple code-along, you won't actually have to submit anything at the end (unlike in the video)."

Which raises the question: should we submit a pull request or not?

**Comment by pickledyamsman** [comment]
@aturkewi This is still part of the lesson and had a student report it today. You have to submit to continue so maybe change it to a readme?

**Comment by aturkewi** [comment]
Thanks for pinging me on this! I toggled it to a readme. All set.

@jonbf for future reference, it will never hurt to put in a pull request. I changed it so it's more clear to what you're doing, but if you had to fork the lab and submit a pull request to pass it, that's totally fine as well.
